name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y valgrind

      - name: make
        run: "make clean; make"

      - name: cppcheck
        run: "make cppcheck"

      - name: Valgrind
        run: "make valgrind"

      - name: Sanitizer
        env:
          ASAN_OPTIONS: detect_leaks=1
        run: "make sanitizer"
